import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

export default function CallsScreen() {
  const { isAuthenticated } = useAuth();
  const callsQuery = trpc.calls.getJoinable.useQuery(undefined, { enabled: isAuthenticated, refetchInterval: 12_000 });
  if (!isAuthenticated) return <ScreenContainer className="px-6 justify-center"><Text style={styles.title}>Cuộc gọi</Text><Text style={styles.copy}>Đăng nhập để xem các phiên thuộc phòng của bạn.</Text><TouchableOpacity style={styles.primary} onPress={() => router.push("/login" as any)}><Text style={styles.primaryText}>Đăng nhập</Text></TouchableOpacity></ScreenContainer>;
  return <ScreenContainer className="px-5"><Text style={styles.kicker}>LIVEKIT</Text><Text style={styles.title}>Cuộc gọi</Text><Text style={styles.copy}>Các phiên đang hoạt động trong những phòng bạn là thành viên.</Text><FlatList data={callsQuery.data ?? []} style={styles.list} contentContainerStyle={(callsQuery.data?.length ?? 0) ? styles.listContent : styles.emptyList} refreshing={callsQuery.isRefetching} onRefresh={() => callsQuery.refetch()} keyExtractor={(item) => String(item.id)} ListEmptyComponent={callsQuery.isLoading ? <View style={styles.empty}><ActivityIndicator color="#4F46E5" /></View> : <View style={styles.empty}><View style={styles.emptyIcon}><MaterialIcons name="video-call" size={30} color="#4F46E5" /></View><Text style={styles.emptyTitle}>Chưa có phiên để tham gia</Text><Text style={styles.emptyCopy}>Bạn có thể bắt đầu gọi từ bất kỳ cuộc trò chuyện nào.</Text></View>} renderItem={({ item }) => <TouchableOpacity style={styles.callCard} onPress={() => router.push(`/call/${item.id}` as any)}><View style={styles.callIcon}><MaterialIcons name="videocam" size={25} color="#4F46E5" /></View><View style={styles.callInfo}><Text style={styles.callTitle}>Cuộc gọi phòng #{item.roomId}</Text><Text style={styles.callCopy}>{item.status === "active" ? "Đang diễn ra" : "Đang đổ chuông"}</Text></View><View style={styles.join}><Text style={styles.joinText}>Tham gia</Text></View></TouchableOpacity>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ kicker: { marginTop: 13, color: "#4F46E5", fontWeight: "800", fontSize: 11, letterSpacing: 1.5 }, title: { fontSize: 30, fontWeight: "800", letterSpacing: -0.7, color: "#172033", marginTop: 2 }, copy: { marginTop: 7, color: "#64748B", lineHeight: 21 }, list: { marginTop: 20 }, listContent: { gap: 10, paddingBottom: 25 }, emptyList: { flexGrow: 1 }, callCard: { borderRadius: 20, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E2E8F0", padding: 14, flexDirection: "row", alignItems: "center" }, callIcon: { width: 48, height: 48, borderRadius: 17, backgroundColor: "#EEF2FF", alignItems: "center", justifyContent: "center" }, callInfo: { flex: 1, marginLeft: 11 }, callTitle: { color: "#172033", fontWeight: "800", fontSize: 15 }, callCopy: { color: "#16A34A", fontSize: 12, marginTop: 4 }, join: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 11, backgroundColor: "#4F46E5" }, joinText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, empty: { flex: 1, alignItems: "center", justifyContent: "center", paddingBottom: 70, paddingHorizontal: 32 }, emptyIcon: { width: 67, height: 67, borderRadius: 24, backgroundColor: "#EEF2FF", justifyContent: "center", alignItems: "center", marginBottom: 15 }, emptyTitle: { color: "#172033", fontSize: 17, fontWeight: "800" }, emptyCopy: { color: "#64748B", textAlign: "center", lineHeight: 20, marginTop: 6 }, primary: { marginTop: 25, height: 52, borderRadius: 16, backgroundColor: "#4F46E5", alignItems: "center", justifyContent: "center" }, primaryText: { color: "#FFFFFF", fontWeight: "800", fontSize: 16 } });
